/* eslint-disable */
// Do not edit this file, it is auto-generated at build time!
// See scripts/bootstrap.ts to modify the generation of this file.
const config = {};
config.sitecoreApiKey = process.env.SITECORE_API_KEY || "{C572A619-8DAC-4F1A-B81D-736231CB5F38}",
config.sitecoreApiHost = process.env.SITECORE_API_HOST || "https://sc102update1cs0434809.sc",
config.jssAppName = process.env.JSS_APP_NAME || "sitenextjs",
config.graphQLEndpointPath = process.env.GRAPH_QL_ENDPOINT_PATH || "/sitecore/api/graph/edge",
config.sitecoreApiHost = "https://62a7-118-101-157-227.ngrok-free.app",
config.graphQLEndpoint = process.env.GRAPH_QL_ENDPOINT || `${config.sitecoreApiHost}${config.graphQLEndpointPath}`;
module.exports = config;